#! /bin/sh

# The /etc/hosts file gets generated by docker to include 
# addresses that we don't want to resolve for the host machine. 

echo '127.0.0.1  localhost  localhost' > /etc/hosts

dnsmasq -k -H /etc/dnsmasq.d/hosts -Z 