version: '2.0' 
services:
    
# To copy the proxy config into the volume:
# dc run  -v $PWD:/source  shell /bin/cp /source/proxy.conf /etc/nginx/conf.d; dc restart nginx
    
  shell:
      image: ubuntu
     
      stdin_open: true
      tty: true
      restart: unless-stopped
      volumes:
        - etc-nginx-conf:/etc/nginx/conf.d
        - etc-nginx-vhost:/etc/nginx/vhost.d
        - usr-share-nginx-html:/usr/share/nginx/html
        - etc-nginx-certs:/etc/nginx/certs:ro
        - etc-dockergen-templates:/etc/docker-gen/templates
    
  nginx:
    image: nginx-proxy
    container_name: proxy_nginx
    build: 
        dockerfile: Dockerfile.nginx
        context: .
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - etc-nginx-conf:/etc/nginx/conf.d
      - etc-nginx-vhost:/etc/nginx/vhost.d
      - usr-share-nginx-html:/usr/share/nginx/html
      - etc-nginx-certs:/etc/nginx/certs:ro


  nginx-gen:
    image: docker-gen
    build: 
        dockerfile: Dockerfile.docker-gen
        context: .
    #command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    command: -notify-sighup proxy_nginx -watch  /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: proxy_nginx-gen
    restart: unless-stopped
    volumes:
      - etc-nginx-conf:/etc/nginx/conf.d
      - etc-nginx-vhost:/etc/nginx/vhost.d
      - usr-share-nginx-html:/usr/share/nginx/html
      - etc-nginx-certs:/etc/nginx/certs:ro
      - etc-dockergen-templates:/etc/docker-gen/templates
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy_nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - etc-nginx-conf:/etc/nginx/conf.d
      - etc-nginx-vhost:/etc/nginx/vhost.d
      - usr-share-nginx-html:/usr/share/nginx/html
      - etc-nginx-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "proxy_nginx-gen"
      NGINX_PROXY_CONTAINER: "proxy_nginx"
      ACME_TOS_HASH: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b
    dns: 
      - 8.8.8.8
      - 8.8.4.4
  
  hello:
      restart: always
      build: docker-hello-world/
      environment:
      - VIRTUAL_HOST=hello.busboom.org
      ports:
        - "8089:80"
      #- LETSENCRYPT_HOST=hello.civicknowledge.com 
      #- LETSENCRYPT_EMAIL=eric@civicknowledge.com
      #- LETSENCRYPT_TEST=true

volumes:
    etc-dockergen-templates: 
    etc-nginx-certs: 
    etc-nginx-conf:
    etc-nginx-vhost: 
    usr-share-nginx-html: 

networks:
  default:
    external:
      name: webproxy